version: 2
updates:
- package-ecosystem: docker
  directory: "/tor_for_piping_server"
  schedule:
    interval: daily
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
  reviewers:
  - nwtgck
  assignees:
  - nwtgck
