name: CI

on: [push, pull_request]

jobs:
  operational_test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install -y tor
    - run: tor --version
    - name: Run tor in background
      run: tor &
    - name: Run onion service
      run: |
        set -eux
         # Build images (to shorten time in docker-compose up)
        docker-compose build
        # Create SSL certificates
        ./create_ssl_certs.sh
        # Run server
        docker-compose up -d
    - name: Wait for onion service to be available
      run: |
        set +o errexit
        # Get onion service host
        server_host=$(sudo cat docker_volumes/tor_hidden_service/hostname)
        while true; do
          torsocks curl -sS ${server_host}/version
          if [ $? = "0" ]; then
            break
          fi
          sleep 2
        done
      timeout-minutes: 2
    - name: Operational test
      run: |
        # Get onion service host
        server_host=$(sudo cat docker_volumes/tor_hidden_service/hostname)
        
        # Get help
        torsocks curl ${server_host}/help

        # Create a file to send
        echo 'hello, world' > /tmp/hello.txt
        # Send and wait for a receiver
        torsocks curl -T /tmp/hello.txt ${server_host}/mypath &
        # Get data as a file
        torsocks curl ${server_host}/mypath > /tmp/download.txt
        # Print downloaded file
        cat  /tmp/download.txt
        # Test the equality
        diff /tmp/hello.txt /tmp/download.txt

        # Print server's log
        docker-compose logs
